services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: keyboard-warrior-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      FRONTEND_URL: http://localhost
      ALLOWED_ORIGINS: http://localhost,http://localhost:80
      DATABASE_PATH: /app/data/database.db
      DATABASE_ENCRYPTION_KEY: ${DATABASE_ENCRYPTION_KEY:-generate-a-secure-32-char-key-for-production}
      JWT_SECRET: ${JWT_SECRET:-generate-a-secure-64-char-secret-for-production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-generate-another-secure-64-char-secret}
      JWT_EXPIRATION: 15m
      JWT_REFRESH_EXPIRATION: 7d
      JWT_ISSUER: keyboard-warrior-api
      JWT_AUDIENCE: keyboard-warrior-app
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-openai-api-key-here}
      OPENAI_MAX_TOKENS: 1000
      OPENAI_TEMPERATURE: 0.8
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      BCRYPT_ROUNDS: 12
      LOG_LEVEL: info
    volumes:
      - backend-data:/app/data
      - backend-logs:/app/logs
    networks:
      - keyboard-warrior-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: keyboard-warrior-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - keyboard-warrior-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  keyboard-warrior-network:
    driver: bridge

volumes:
  backend-data:
    driver: local
  backend-logs:
    driver: local